make_files:
  stage: build
  script:
    - CPPFLAGS="-D FLEXT_INLINE -I $HOME/flext/source" make
  artifacts:
    paths:
      - $CI_PROJECT_DIR/*.pd_*
    expire_in: 1h

deploy_files:
  stage: deploy
  script:
    - echo $CI_PROJECT_DIR/*.pd_*
