# pool - hierarchical storage object for PD and Max/MSP
# Copyright (C) 2002-2004 Thomas Grill (xovo@gmx.net)
#
# Makefile for MSVC++ 6 and 7
#
# usage:
# to build run "make -f makefile.pd-msvc"
#

!include config-pd-msvc.txt

!include make-files.txt

!include $(FLEXTPATH)\build\makefile.pd-msvc
