# pool - hierarchical storage object for PD and Max/MSP
# Copyright (C) 2002-2004 Thomas Grill (xovo@gmx.net)
#
# Makefile for gcc @ darwin (OSX)
#
# usage:
# to build run "make -f makefile.pd-darwin"
# to install (as root), do "make -f makefile.pd-darwin install"
#

CONFIG=config-pd-darwin.txt

include $(CONFIG)

include make-files.txt

include $(FLEXTPATH)/build/makefile.pd-darwin





