# pool - hierarchical storage object for PD and Max/MSP
# Copyright (C) 2002-2004 Thomas Grill (xovo@gmx.net)
#
# Makefile for gcc @ linux
#
# usage:
# to build run "make -f makefile.pd-linux"
# to install (as root), do "make -f makefile.pd-linux install"
#

CONFIG=config-pd-linux.txt

include $(CONFIG)

include make-files.txt

include $(FLEXTPATH)/build/makefile.pd-linux
