# pool - hierarchical storage object for PD and Max/MSP
# Copyright (C) 2002-2004 Thomas Grill
#
# Makefile for BorlandC++ 
#
# usage: make -f makefile.pd-bcc
#
# ---------------------------------------------

!include config-pd-bcc.txt

!include make-files.txt

!include $(FLEXTPATH)\build\makefile.pd-bcc
